# utils/extractor_helper.py
import os
import sys
import json
import shutil
import subprocess

def get_paks_dir(palworld_exe: str) -> str | None:
    """
    Safely calculates the Palworld Paks folder directory path based on the executable path.
    Handles both root executable and Win64-Shipping executable paths.
    """
    if not palworld_exe or not os.path.exists(palworld_exe):
        return None
    
    exe_lower = palworld_exe.lower()
    if "binaries" in exe_lower:
        return os.path.normpath(os.path.join(os.path.dirname(palworld_exe), "..", "..", "Content", "Paks"))
    else:
        return os.path.normpath(os.path.join(os.path.dirname(palworld_exe), "Pal", "Content", "Paks"))

def extract_game_files(settings: dict, relative_paths: list[str], output_dir: str, format_type: str = "raw") -> tuple[bool, str]:
    """
    Runs cue4parse.exe to headlessly extract a list of game files from Palworld .pak archives.
    Allows specifying format_type (e.g. "json", "raw", "csv").
    Returns (success_boolean, status_message).
    """
    palworld_exe = settings.get("palworld_exe", "")
    paks_dir = get_paks_dir(palworld_exe)
    if not paks_dir or not os.path.exists(paks_dir):
        return False, f"Paks directory not found or Palworld.exe path is invalid: {paks_dir}"

    # Resolve dependency absolute paths inside our repository structure
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cue4parse_exe = os.path.normpath(os.path.join(repo_root, "deps", "cue4parse.exe"))
    usmap_path = os.path.normpath(os.path.join(repo_root, "deps", "Mappings.usmap"))

    if not os.path.exists(cue4parse_exe):
        return False, f"Missing cue4parse.exe dependency at {cue4parse_exe}"
    if not os.path.exists(usmap_path):
        return False, f"Missing Mappings.usmap dependency at {usmap_path}"

    os.makedirs(output_dir, exist_ok=True)

    # Compile the CLI commands
    cmd = [
        cue4parse_exe,
        "-i", paks_dir,
        "-o", output_dir,
        "-m", usmap_path,
        "-g", "GAME_UE5_1",
        "-f", format_type,
        "-y"
    ]

    for rel_path in relative_paths:
        cmd.extend(["-p", rel_path])

    try:
        creation_flags = subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
        result = subprocess.run(cmd, capture_output=True, text=True, creationflags=creation_flags)
        
        if result.returncode != 0:
            error_details = result.stderr or result.stdout
            return False, f"cue4parse exited with code {result.returncode}. Details: {error_details}"
            
        return True, "Extraction completed successfully."
    except Exception as e:
        return False, f"Failed to execute cue4parse.exe process: {e}"

def extract_single_file(settings: dict, relative_path: str, output_dir: str) -> bool:
    """
    Helper wrapper to extract a single file directly from paks.
    Logs warnings internally to terminal console if the process fails.
    """
    success, msg = extract_game_files(settings, [relative_path], output_dir)
    if not success:
        print(f"[Extractor Helper] Extraction failed for {relative_path}: {msg}", flush=True)
    return success

def build_pal_names_map(settings: dict) -> tuple[bool, str]:
    """
    Extracts the latest English localization table from the game paks,
    translates the serialized structure, and builds the local pal_names_map.json.
    Also extracts all vanilla Pal icons from the archives to dynamically populate the UI.
    """
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_map_path = os.path.join(repo_root, "pal_names_map.json")
    
    # Temporary output directory for text extraction
    temp_out = os.path.join(repo_root, "temp_db_extract")
    relative_asset_path = "Pal/Content/L10N/en/Pal/DataTable/Text/DT_PalNameText_Common.uasset"
    
    # Extract deserialized JSON format directly
    success, msg = extract_game_files(settings, [relative_asset_path], temp_out, format_type="json")
    if not success:
        return False, f"Failed to extract text data table: {msg}"
        
    extracted_file_path = os.path.normpath(os.path.join(
        temp_out, "Pal", "Content", "L10N", "en", "Pal", "DataTable", "Text", "DT_PalNameText_Common.json"
    ))
    
    if not os.path.exists(extracted_file_path):
        shutil.rmtree(temp_out, ignore_errors=True)
        return False, f"Extracted file not found at expected path: {extracted_file_path}"
        
    try:
        # FIXED: Explicitly use utf-8-sig to automatically discard the UTF-8 BOM signature generated by cue4parse
        with open(extracted_file_path, "r", encoding="utf-8-sig") as f:
            raw_data = json.load(f)
            
        # Parse standard array-wrapped DataTable object output by cue4parse
        data_table_obj = None
        if isinstance(raw_data, list):
            for obj in raw_data:
                if obj.get("Type") == "DataTable" and "Rows" in obj:
                    data_table_obj = obj
                    break
        elif isinstance(raw_data, dict):
            if raw_data.get("Type") == "DataTable" and "Rows" in raw_data:
                data_table_obj = raw_data
                
        if not data_table_obj:
            shutil.rmtree(temp_out, ignore_errors=True)
            return False, "Extracted JSON does not contain valid DataTable Rows."
            
        raw_rows = data_table_obj["Rows"]
        transformed_rows = {}
        
        for k, v in raw_rows.items():
            # Clean row keys (e.g. PAL_NAME_Alpaca -> Alpaca)
            clean_key = k
            if k.startswith("PAL_NAME_"):
                clean_key = k[len("PAL_NAME_"):]
                
            text_data = v.get("TextData", {})
            transformed_text_data = {
                "Namespace": text_data.get("Namespace", "DT_PalNameText_Common"),
                "Key": clean_key,
                "SourceString": text_data.get("SourceString", ""),
                "LocalizedString": text_data.get("LocalizedString", "")
            }
            
            transformed_rows[clean_key] = {
                "TextData": transformed_text_data
            }
            
        output_payload = {
            "Rows": transformed_rows
        }
        
        # Save output map back to root path directory
        with open(target_map_path, "w", encoding="utf-8") as f_out:
            json.dump(output_payload, f_out, indent=4)
            
        # Cleanup temp directory
        shutil.rmtree(temp_out, ignore_errors=True)
        
        # --- EXTRACT ALL VANILLA PAL ICONS ---
        fmodel_base = settings.get("fmodel_output", "")
        if fmodel_base:
            icon_relative_dir = "Pal/Content/Pal/Texture/PalIcon/Normal"
            icon_export_root = os.path.join(fmodel_base, "Exports")
            
            print("[Extractor] Extracting game Pal Icons...", flush=True)
            success_icons, msg_icons = extract_game_files(
                settings,
                [f"{icon_relative_dir}/*"],
                icon_export_root,
                format_type="auto"
            )
            if success_icons:
                # Sanitize UE binary leftovers from the extracted icons folder
                extracted_icon_dir = os.path.normpath(os.path.join(icon_export_root, icon_relative_dir))
                if os.path.exists(extracted_icon_dir):
                    redundant_extensions = (".uasset", ".uexp", ".ubulk")
                    for root, _, files in os.walk(extracted_icon_dir):
                        for file in files:
                            if file.lower().endswith(redundant_extensions):
                                try: os.remove(os.path.join(root, file))
                                except OSError: pass
            else:
                print(f"[Extractor] Warning: Failed to extract vanilla Pal Icons: {msg_icons}", flush=True)

        return True, "Pal Names Map built and vanilla Pal Icons extracted successfully."
        
    except Exception as e:
        shutil.rmtree(temp_out, ignore_errors=True)
        return False, f"Error processing extracted data table: {e}"

def extract_pal_assets(settings: dict, pal_name: str, category: str = "Monster") -> tuple[bool, str]:
    """
    Extracts all visual assets (skeletal mesh, textures, material instances)
    for a given Pal directly from the game's Paks.
    """
    fmodel_root = settings.get("fmodel_output", "")
    if not fmodel_root:
        return False, "FModel output folder is not configured."
        
    export_root = os.path.join(fmodel_root, "Exports")
    pal_relative_dir = f"Pal/Content/Pal/Model/Character/{category}/{pal_name}"
    
    # Pass 1: Auto conversion of Mesh and Textures (SkeletalMesh -> .psk, Texture2D -> .png)
    success_raw, msg_raw = extract_game_files(
        settings, 
        [f"{pal_relative_dir}/*"], 
        export_root, 
        format_type="auto"
    )
    if not success_raw:
        return False, f"Failed to extract and convert mesh/texture assets: {msg_raw}"
        
    # Pass 2: JSON serialization extraction of Material Instances (MaterialInstanceConstant -> .json)
    success_json, msg_json = extract_game_files(
        settings, 
        [f"{pal_relative_dir}/MI_*"], 
        export_root, 
        format_type="json"
    )
    if not success_json:
        # Don't fail the whole block if some specific auxiliary test targets lack MI files
        print(f"[Extractor] Warning: Material instance JSON extraction had issues: {msg_json}", flush=True)
        
    # Pass 3: Post-extraction sanitation. Wipe raw engine binaries while preserving converted outputs and JSONs
    pal_dir = os.path.normpath(os.path.join(fmodel_root, "Exports", "Pal", "Content", "Pal", "Model", "Character", category, pal_name))
    if os.path.exists(pal_dir):
        redundant_extensions = (".uasset", ".uexp", ".ubulk")
        for root, _, files in os.walk(pal_dir):
            for file in files:
                if file.lower().endswith(redundant_extensions):
                    file_path = os.path.join(root, file)
                    try:
                        os.remove(file_path)
                    except OSError as e:
                        print(f"[Extractor Cleanup] Warning: Failed to remove redundant asset {file}: {e}", flush=True)

    return True, f"Successfully extracted visual assets for {pal_name}."